country_map = {"<pad>": 0,
               "<sos>": 1,
               "<eos>": 2,
               "Yellow_A": 3,
               "Yellow_B": 4,
               "Yellow_C": 5,
               "Yellow_D": 6,
               "Blue_A": 7,
               "Blue_B": 8,
               "Blue_C": 9,
               "Blue_D": 10,
               "Green_A": 11,
               "Green_B": 12,
               "Green_C": 13,
               "Green_D": 14,
               "Green_E": 15,
               "Purple_A": 16,
               "Purple_B": 17,
               "Purple_C": 18,
               "Purple_D": 19,
               "Purple_E": 20,
               "Red_A": 21,
               "Red_B": 22,
               "Red_C": 23}

#grey player
map_player_1 = [
 [["Yellow_B",4], ["Yellow_C",5], ["Red_A",1], ["Red_B",2], ["Red_C",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",1], ["Yellow_D",2], ["Green_A",5], ["Blue_C",3], ["Blue_D",3], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",4], ["Yellow_B",2], ["Green_C",1], ["Green_D",4], ["Green_E",3], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_A",4], ["Red_B",3], ["Purple_A",5], ["Blue_C",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_A",5], ["Green_B",1], ["Green_C",2], ["Green_D",2], ["Green_E",4], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Red_B",4], ["Red_C",2], ["Purple_E",4], ["Blue_A",3], ["Blue_B",1], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_C",4], ["Green_D",4], ["Green_E",4], ["Red_A",1], ["Purple_A",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_B",5], ["Yellow_C",1], ["Yellow_D",2], ["Green_C",3], ["Blue_A",3], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_A",3], ["Green_E",4], ["Purple_A",4], ["Blue_B",1], ["Blue_D",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_C",4], ["Green_D",4], ["Red_A",4], ["Blue_A",1], ["Blue_B",1], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_B",1], ["Green_E",2], ["Red_B",1], ["Blue_B",8], ["Blue_C",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",7], ["Yellow_D",2], ["Green_B",1], ["Green_C",1], ["Purple_C",1], ["Purple_D",1], ["Blue_C",1]],
 [["Yellow_B",5], ["Yellow_C",4], ["Yellow_D",1], ["Purple_B",2], ["Purple_C",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_C",4], ["Green_E",4], ["Blue_A",5], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Red_B",7], ["Red_C",7], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
]

#black player
map_player_2 = [
 [["Green_E",2], ["Purple_A",5], ["Purple_B",1], ["Blue_A",3], ["Blue_B",3], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_C",4], ["Green_D",3], ["Purple_C",4], ["Purple_E",1], ["Blue_A",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_C",1], ["Yellow_D",1], ["Red_A",5], ["Purple_E",2], ["Blue_B",5], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_B",2], ["Yellow_C",3], ["Red_C",3], ["Purple_C",1], ["Purple_D",1], ["Purple_E",4], ["<pad>", "<pad>"]],
 [["Yellow_D",5], ["Red_A",4], ["Purple_A",5], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_A",3], ["Green_D",3], ["Red_A",2], ["Purple_C",1], ["Purple_D",3], ["Blue_C",2], ["<pad>", "<pad>"]],
 [["Yellow_C",1], ["Yellow_D",3], ["Green_A",2], ["Green_B",6], ["Blue_D",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",1], ["Red_C",4], ["Purple_B",2], ["Purple_C",1], ["Purple_E",4], ["Blue_C",2], ["<pad>", "<pad>"]],
 [["Yellow_B",5], ["Yellow_D",2], ["Green_B",4], ["Purple_D",3], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",2], ["Yellow_C",4], ["Red_B",4], ["Blue_C",2], ["Blue_D",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Purple_A",7], ["Purple_B",1], ["Purple_E",6], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_A",6], ["Red_A",2], ["Red_C",1], ["Purple_A",5], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Green_D",5], ["Blue_A",3], ["Blue_B",4], ["Blue_D",2], ["<pad>", "<pad>"], ["<pad>", "<pad>"], ["<pad>", "<pad>"]],
 [["Yellow_A",1], ["Green_A",2], ["Red_C",4], ["Purple_C",1], ["Purple_E",4], ["Blue_C",2], ["<pad>", "<pad>"]],
 [["Yellow_A",1], ["Yellow_D",2], ["Green_D",6], ["Red_A",2], ["Purple_B",1], ["Blue_C",2], ["<pad>", "<pad>"]],
]